apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - target: {kind: ExternalSecret, name: cluster-template-pc-credentials}
    patch: |-
      - {op: replace, path: /metadata/name, value: it-cluster-pc-credentials}
      - {op: replace, path: /metadata/namespace, value: it}
      - {op: replace, path: /spec/target/name, value: it-cluster-pc-credentials}
  - target: {kind: ExternalSecret, name: cluster-template-pc-credentials-for-csi}
    patch: |-
      - {op: replace, path: /metadata/name, value: it-cluster-pc-credentials-for-csi}
      - {op: replace, path: /metadata/namespace, value: it}
      - {op: replace, path: /spec/target/name, value: it-cluster-pc-credentials-for-csi}
  - target: {kind: ExternalSecret, name: cluster-template-pc-credentials-for-konnector-agent}
    patch: |-
      - {op: replace, path: /metadata/name, value: it-cluster-pc-credentials-for-konnector-agent}
      - {op: replace, path: /metadata/namespace, value: it}
      - {op: replace, path: /spec/target/name, value: it-cluster-pc-credentials-for-konnector-agent}
