apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - target: {kind: ExternalSecret, name: cluster-template-pc-credentials}
    patch: |-
      - {op: replace, path: /metadata/name, value: finance-cluster-pc-credentials}
      - {op: replace, path: /metadata/namespace, value: finance}
      - {op: replace, path: /spec/target/name, value: finance-cluster-pc-credentials}
      - {op: replace, path: /spec/data/0/remoteRef/key, value: global-nutanix-credentials-2}
      - {op: replace, path: /spec/data/1/remoteRef/key, value: global-nutanix-credentials-2}
  - target: {kind: ExternalSecret, name: cluster-template-pc-credentials-for-csi}
    patch: |-
      - {op: replace, path: /metadata/name, value: finance-cluster-pc-credentials-for-csi}
      - {op: replace, path: /metadata/namespace, value: finance}
      - {op: replace, path: /spec/target/name, value: finance-cluster-pc-credentials-for-csi}
      - {op: replace, path: /spec/data/0/remoteRef/key, value: global-nutanix-credentials-2}
      - {op: replace, path: /spec/data/1/remoteRef/key, value: global-nutanix-credentials-2}
      - {op: replace, path: /spec/data/2/remoteRef/key, value: global-nutanix-credentials-2}
  - target: {kind: ExternalSecret, name: cluster-template-pc-credentials-for-konnector-agent}
    patch: |-
      - {op: replace, path: /metadata/name, value: finance-cluster-pc-credentials-for-konnector-agent}
      - {op: replace, path: /metadata/namespace, value: finance}
      - {op: replace, path: /spec/target/name, value: finance-cluster-pc-credentials-for-konnector-agent}
      - {op: replace, path: /spec/data/0/remoteRef/key, value: global-nutanix-credentials-2}
      - {op: replace, path: /spec/data/1/remoteRef/key, value: global-nutanix-credentials-2}