apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-template-pc-credentials
  namespace: workspace-template
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: nutanix-provider-01
    kind: SecretStore
  target:
    name: cluster-template-pc-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        credentials: |
          {{ list (dict "type" "basic_auth" "data" (dict "prismCentral" (dict "username" .username "password" .password))) | toJson }}
  data:
    - secretKey: username
      remoteRef:
        key: global-nutanix-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: global-nutanix-credentials
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-template-pc-credentials-for-csi
  namespace: workspace-template
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: nutanix-provider-01
    kind: SecretStore
  target:
    name: cluster-template-pc-credentials-for-csi
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        key: |-
          {{ printf "%s:%s:%s" (.prismURL | trimPrefix "https://" | trimPrefix "http://") .username .password }}
  data:
    - secretKey: prismURL
      remoteRef:
        key: global-nutanix-credentials
        property: prismURL
    - secretKey: username
      remoteRef:
        key: global-nutanix-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: global-nutanix-credentials
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-template-pc-credentials-for-konnector-agent
  namespace: workspace-template
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: nutanix-provider-01
    kind: SecretStore
  target:
    name: cluster-template-pc-credentials-for-konnector-agent
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: global-nutanix-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: global-nutanix-credentials
        property: password
