apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: nutanix-provider-01
  namespace: workspace-template
spec:
  provider:
    kubernetes:
      remoteNamespace: capx-system
      server:
        url: kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-secret-reader
          namespace: workspace-template
