apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- overlays/engineering/engineering-cluster
- overlays/engineering/engineering-cluster-2
- overlays/finance/finance-cluster
- overlays/it/it-cluster
- overlays/sales/sales-cluster